package Frame;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

/**
 *
 * @author 00
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);

        suhu();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();
        suhu = new javax.swing.JLabel();
        pH = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        hs = new javax.swing.JLabel();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, 30));

        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, 40, 40));

        suhu.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 50)); // NOI18N
        getContentPane().add(suhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 170, 130));

        pH.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 50)); // NOI18N
        getContentPane().add(pH, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 160, 140));

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 90, 30));

        hs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hsMouseClicked(evt);
            }
        });
        getContentPane().add(hs, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 90, 30));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dashboard.png"))); // NOI18N
        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
           
    Connection con  = Koneksi.getKoneksi();
    ResultSet rs =null;
    PreparedStatement pst = null;
    
    
    
    public void suhu(){
        try{
            String sql = "SELECT * FROM `histori` ORDER BY `histori`.`id` DESC";
            java.sql.Connection con = (Connection) Koneksi.getKoneksi();
            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            java.sql.ResultSet rs  = ps.executeQuery(sql);
            if (rs.next()){
                suhu.setText(rs.getString(2));
                pH.setText(rs.getString(3));
        }else{
                JOptionPane.showMessageDialog(null, "error");
                }
        }catch(Exception e){
            
    }
    }
    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        this.setVisible(false);
        new Histori().setVisible(true);
    }//GEN-LAST:event_MenuMouseClicked

    private void hsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hsMouseClicked
        this.setVisible(false);
        new Histori().setVisible(true);
        
    }//GEN-LAST:event_hsMouseClicked

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
          Dashboard ds = new Dashboard();
        ds.setVisible(true);
        dispose();
    }//GEN-LAST:event_refreshMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel hs;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel pH;
    private javax.swing.JLabel refresh;
    private javax.swing.JLabel suhu;
    // End of variables declaration//GEN-END:variables
}
